version: '3.9'

services:
  redis_cache:
    image: redis:alpine
    container_name: TrekB_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_cache_volume:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: on-failure

  redis_broker:
    image: redis:alpine
    container_name: TrekB_broker
    ports:
      - "6380:6379"
    volumes:
      - redis_broker_volume:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: on-failure

  bot:
    build: .
    image: trekb-bot:prod_v1.0.0
    container_name: TrekB_bot_prod
    env_file:
      - .env
    environment:
      - CACHE_HOST=TrekB_cache
      - CACHE_PORT=6379
      - BROKER_HOST=TrekB_broker
      - BROKER_PORT=6379
    ports:
      - "8000:8000"
    command: python app.py
    restart: always
    depends_on:
      - redis_cache
      - redis_broker

volumes:
  redis_cache_volume:
  redis_broker_volume:
